// <auto-generated />
using System;
using HospitalCheckupSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalCheckupSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260217044613_AddMedicalCheckupAggregate")]
    partial class AddMedicalCheckupAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalCheckupSystem.Domain.Entities.MedicalCheckup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckupDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("McuNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MedicalCheckups", (string)null);
                });

            modelBuilder.Entity("HospitalCheckupSystem.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mrn")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalCheckupSystem.Domain.Entities.MedicalCheckup", b =>
                {
                    b.OwnsOne("HospitalCheckupSystem.Domain.Entities.Anamnesis", "Anamnesis", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Alcohol")
                                .HasColumnType("bit");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Complaints")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FamilyHistory")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("MedicalCheckupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PastIllness")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Smoking")
                                .HasColumnType("bit");

                            b1.Property<string>("WorkHazards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicalCheckupId")
                                .IsUnique();

                            b1.ToTable("CheckupAnamneses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalCheckupId");
                        });

                    b.OwnsMany("HospitalCheckupSystem.Domain.Entities.LabResultItem", "LabResults", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsNormal")
                                .HasColumnType("bit");

                            b1.Property<Guid>("MedicalCheckupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("NormalMax")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("NormalMin")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("TestName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicalCheckupId");

                            b1.ToTable("CheckupLabResults", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalCheckupId");
                        });

                    b.OwnsOne("HospitalCheckupSystem.Domain.Entities.MedicalConclusion", "Conclusion", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Diagnosis")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Fit")
                                .HasColumnType("bit");

                            b1.Property<Guid>("MedicalCheckupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Recommendation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicalCheckupId")
                                .IsUnique();

                            b1.ToTable("CheckupConclusions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalCheckupId");
                        });

                    b.OwnsOne("HospitalCheckupSystem.Domain.Entities.PhysicalExam", "PhysicalExam", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Abdomen")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ENT")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Eyes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GeneralAppearance")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Heart")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Lungs")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("MedicalCheckupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Neurology")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicalCheckupId")
                                .IsUnique();

                            b1.ToTable("CheckupPhysicalExams", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalCheckupId");
                        });

                    b.OwnsOne("HospitalCheckupSystem.Domain.Entities.VitalSigns", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("BMI")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("Diastolic")
                                .HasColumnType("int");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("MedicalCheckupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Pulse")
                                .HasColumnType("int");

                            b1.Property<int>("Systolic")
                                .HasColumnType("int");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicalCheckupId")
                                .IsUnique();

                            b1.ToTable("CheckupVitals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalCheckupId");
                        });

                    b.Navigation("Anamnesis");

                    b.Navigation("Conclusion");

                    b.Navigation("LabResults");

                    b.Navigation("PhysicalExam");

                    b.Navigation("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
